// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwVcuquEzuJzCgKgkWB7CaCqeYQbPdTuM',
    appId: '1:374280878102:web:86395dbab92c21839bdd37',
    messagingSenderId: '374280878102',
    projectId: 'thatsboy-6af59',
    authDomain: 'thatsboy-6af59.firebaseapp.com',
    storageBucket: 'thatsboy-6af59.appspot.com',
    measurementId: 'G-MNLD2MNPYG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeDHAi0c2HaUubSc8sH1poPNWAOFlJAyU',
    appId: '1:374280878102:android:35ffe1a3ccfc6c509bdd37',
    messagingSenderId: '374280878102',
    projectId: 'thatsboy-6af59',
    storageBucket: 'thatsboy-6af59.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5CJw1n4azH5V6RwkPCyvfbjdXaULSSwU',
    appId: '1:374280878102:ios:e9f3e134cda8418b9bdd37',
    messagingSenderId: '374280878102',
    projectId: 'thatsboy-6af59',
    storageBucket: 'thatsboy-6af59.appspot.com',
    iosBundleId: 'com.example.myBanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5CJw1n4azH5V6RwkPCyvfbjdXaULSSwU',
    appId: '1:374280878102:ios:e9f3e134cda8418b9bdd37',
    messagingSenderId: '374280878102',
    projectId: 'thatsboy-6af59',
    storageBucket: 'thatsboy-6af59.appspot.com',
    iosBundleId: 'com.example.myBanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwVcuquEzuJzCgKgkWB7CaCqeYQbPdTuM',
    appId: '1:374280878102:web:9aa6b99d4199898a9bdd37',
    messagingSenderId: '374280878102',
    projectId: 'thatsboy-6af59',
    authDomain: 'thatsboy-6af59.firebaseapp.com',
    storageBucket: 'thatsboy-6af59.appspot.com',
    measurementId: 'G-TFGFFP67N1',
  );

}